name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Add GitHub.com to known_hosts
        run: ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Add your EC2 instance to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Copy code to EC2
        run: scp -r -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no ./* ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/copy_paste
