name: Deploy to EC2

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy code to EC2
        run: |
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
          scp -r -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no ./* ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/copy_paste
